[versions]
agp = "8.5.2"
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "34"
androidx-activityCompose = "1.9.3"
androidx-lifecycle = "2.8.4"
compose-multiplatform = "1.9.3"
kotlin = "2.1.0"
jetbrainsKotlinJvm = "1.9.0"
maven-publish = "0.30.0"
okio = "3.9.0"
kotlin-io = "0.6.0"
kotlin-io-okio = "0.7.0"
koin-version = "4.0.2"
ksp-version = "2.1.0-1.0.29"
print = "1.0.0"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
okio = { group = "com.squareup.okio", name = "okio", version.ref = "okio" }
kotlin-io = { group = "org.jetbrains.kotlinx", name = "kotlinx-io-core", version.ref = "kotlin-io" }
kotlin-io-okio = { group = "org.jetbrains.kotlinx", name = "kotlinx-io-okio", version.ref = "kotlin-io-okio" }
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin-version" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin-version" }
koin-compose = {module = "io.insert-koin:koin-compose", version.ref = "koin-version"}
print = { group = "androidx.print", name = "print", version.ref = "print" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
kotlinKsp = { id = "com.google.devtools.ksp", version.ref = "ksp-version" }